In [27]:
d1 = {'key1' : [1,2,3,4,5,'sudh']  , 
      'key2' : [7,8,9,10,11,12],
      'key3' : [13,14,15,16,17,18],
      'key4' : [19,20,21,22,23,24]
      }

In [28]:
d1

{'key1': [1, 2, 3, 4, 5, 'sudh'],
 'key2': [7, 8, 9, 10, 11, 12],
 'key3': [13, 14, 15, 16, 17, 18],
 'key4': [19, 20, 21, 22, 23, 24]}

In [29]:
import pandas as pd

In [77]:
df1 = pd.DataFrame(d1 , index = ['a','b','c','d' , 'e','f'] , name = "aman" , "chawla","key3" , "key4")

SyntaxError: positional argument follows keyword argument (1356263938.py, line 1)

In [31]:
d2 = {'key1' : [1,2,3,4,5,'sudh'] , 
      'key2' : [7,8,9,'aman',11,12],
      'key3' : [13,14,'pwskills',16,17,18],
      'key4' : [19,20,21,'ineuron',23,24]
      }

In [32]:
df2 = pd.DataFrame(d2)

In [33]:
df1

key1  key2  key3  key4
a     1     7    13    19
b     2     8    14    20
c     3     9    15    21
d     4    10    16    22
e     5    11    17    23
f  sudh    12    18    24

In [34]:
df2

key1  key2      key3     key4
0     1     7        13       19
1     2     8        14       20
2     3     9  pwskills       21
3     4  aman        16  ineuron
4     5    11        17       23
5  sudh    12        18       24

In [35]:
pd.merge(df1,df2)

key1 key2 key3 key4
0     1    7   13   19
1     2    8   14   20
2     5   11   17   23
3  sudh   12   18   24

In [36]:
pd.merge(df1,df2 , how = 'inner', on = 'key1')

key1  key2_x  key3_x  key4_x key2_y    key3_y   key4_y
0     1       7      13      19      7        13       19
1     2       8      14      20      8        14       20
2     3       9      15      21      9  pwskills       21
3     4      10      16      22   aman        16  ineuron
4     5      11      17      23     11        17       23
5  sudh      12      18      24     12        18       24

In [40]:
df1

key1  key2  key3  key4
a     1     7    13    19
b     2     8    14    20
c     3     9    15    21
d     4    10    16    22
e     5    11    17    23
f  sudh    12    18    24

In [41]:
df2

key1  key2      key3     key4
0     1     7        13       19
1     2     8        14       20
2     3     9  pwskills       21
3     4  aman        16  ineuron
4     5    11        17       23
5  sudh    12        18       24

In [42]:
pd.merge(df1,df2 , how = 'inner', on = 'key4')

key1_x  key2_x  key3_x key4 key1_y key2_y    key3_y
0      1       7      13   19      1      7        13
1      2       8      14   20      2      8        14
2      3       9      15   21      3      9  pwskills
3      5      11      17   23      5     11        17
4   sudh      12      18   24   sudh     12        18

In [44]:
pd.merge(df1,df2 , how = 'left', on = 'key4') 

key1_x  key2_x  key3_x key4 key1_y key2_y    key3_y
0      1       7      13   19      1      7        13
1      2       8      14   20      2      8        14
2      3       9      15   21      3      9  pwskills
3      4      10      16   22    NaN    NaN       NaN
4      5      11      17   23      5     11        17
5   sudh      12      18   24   sudh     12        18

In [45]:
pd.merge(df1,df2 , how = 'right', on = 'key4') 

/tmp/ipykernel_77/3409485711.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2 , how = 'right', on = 'key4')


key1_x  key2_x  key3_x     key4 key1_y key2_y    key3_y
0      1     7.0    13.0     19.0      1      7        13
1      2     8.0    14.0     20.0      2      8        14
2      3     9.0    15.0     21.0      3      9  pwskills
3    NaN     NaN     NaN  ineuron      4   aman        16
4      5    11.0    17.0     23.0      5     11        17
5   sudh    12.0    18.0     24.0   sudh     12        18

In [46]:
df1

key1  key2  key3  key4
a     1     7    13    19
b     2     8    14    20
c     3     9    15    21
d     4    10    16    22
e     5    11    17    23
f  sudh    12    18    24

In [47]:
df2

key1  key2      key3     key4
0     1     7        13       19
1     2     8        14       20
2     3     9  pwskills       21
3     4  aman        16  ineuron
4     5    11        17       23
5  sudh    12        18       24

In [49]:
pd.merge(df1,df2 , how = 'outer' , on =  'key4')

/tmp/ipykernel_77/2366744945.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2 , how = 'outer' , on =  'key4')


key1_x  key2_x  key3_x     key4 key1_y key2_y    key3_y
0      1     7.0    13.0     19.0      1      7        13
1      2     8.0    14.0     20.0      2      8        14
2      3     9.0    15.0     21.0      3      9  pwskills
3      4    10.0    16.0     22.0    NaN    NaN       NaN
4      5    11.0    17.0     23.0      5     11        17
5   sudh    12.0    18.0     24.0   sudh     12        18
6    NaN     NaN     NaN  ineuron      4   aman        16

In [50]:
pd.merge(df1,df2 , how = 'outer' , on =  ['key4','key1'])

/tmp/ipykernel_77/1178296085.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2 , how = 'outer' , on =  ['key4','key1'])


key1  key2_x  key3_x     key4 key2_y    key3_y
0     1     7.0    13.0     19.0      7        13
1     2     8.0    14.0     20.0      8        14
2     3     9.0    15.0     21.0      9  pwskills
3     4    10.0    16.0     22.0    NaN       NaN
4     5    11.0    17.0     23.0     11        17
5  sudh    12.0    18.0     24.0     12        18
6     4     NaN     NaN  ineuron   aman        16

In [71]:
d11 = {'a' : [1,2,3,4,5,'sudh']  , 
      'b' : [7,8,9,10,11,12],
      'c' : [13,14,15,16,17,18],
      'd' : [19,20,21,22,23,24]
      }

In [72]:
d12 = {'key1' : [1,2,3,4,5,'sudh'] , 
      'key2' : [7,8,9,'aman',11,12],
      'key3' : [13,14,'pwskills',16,17,18],
      'key4' : [19,20,21,'ineuron',23,24]
      }

In [101]:
df11 = pd.DataFrame(d11 , index = [1,2,3,4, 'e','f'] )

In [89]:
df12

key1  key2      key3     key4
0     1     7        13       19
1     2     8        14       20
2     3     9  pwskills       21
3     4  aman        16  ineuron
4     5    11        17       23
5  sudh    12        18       24

In [102]:
df12 = pd.DataFrame(d12 , index = ["a",2,3,4, 'e','f'])

In [103]:
pd.merge(df11,df12 , how = 'left' , left_on = 'a' , right_on = 'key1')

a   b   c   d  key1  key2      key3     key4
0     1   7  13  19     1     7        13       19
1     2   8  14  20     2     8        14       20
2     3   9  15  21     3     9  pwskills       21
3     4  10  16  22     4  aman        16  ineuron
4     5  11  17  23     5    11        17       23
5  sudh  12  18  24  sudh    12        18       24

In [104]:
df11

a   b   c   d
1     1   7  13  19
2     2   8  14  20
3     3   9  15  21
4     4  10  16  22
e     5  11  17  23
f  sudh  12  18  24

In [105]:
df12

key1  key2      key3     key4
a     1     7        13       19
2     2     8        14       20
3     3     9  pwskills       21
4     4  aman        16  ineuron
e     5    11        17       23
f  sudh    12        18       24

In [106]:
df11.join(df12)  ## match based on index  present or not in both 

a   b   c   d  key1  key2      key3     key4
1     1   7  13  19   NaN   NaN       NaN      NaN
2     2   8  14  20     2     8        14       20
3     3   9  15  21     3     9  pwskills       21
4     4  10  16  22     4  aman        16  ineuron
e     5  11  17  23     5    11        17       23
f  sudh  12  18  24  sudh    12        18       24

In [107]:
df11.join(df12 , how = 'outer')

a     b     c     d  key1  key2      key3     key4
1     1   7.0  13.0  19.0   NaN   NaN       NaN      NaN
2     2   8.0  14.0  20.0     2     8        14       20
3     3   9.0  15.0  21.0     3     9  pwskills       21
4     4  10.0  16.0  22.0     4  aman        16  ineuron
a   NaN   NaN   NaN   NaN     1     7        13       19
e     5  11.0  17.0  23.0     5    11        17       23
f  sudh  12.0  18.0  24.0  sudh    12        18       24

In [108]:
df11.join(df12 , how = 'inner')

a   b   c   d  key1  key2      key3     key4
2     2   8  14  20     2     8        14       20
3     3   9  15  21     3     9  pwskills       21
4     4  10  16  22     4  aman        16  ineuron
e     5  11  17  23     5    11        17       23
f  sudh  12  18  24  sudh    12        18       24

In [109]:
df11.join(df12 , how = 'right')

a     b     c     d  key1  key2      key3     key4
a   NaN   NaN   NaN   NaN     1     7        13       19
2     2   8.0  14.0  20.0     2     8        14       20
3     3   9.0  15.0  21.0     3     9  pwskills       21
4     4  10.0  16.0  22.0     4  aman        16  ineuron
e     5  11.0  17.0  23.0     5    11        17       23
f  sudh  12.0  18.0  24.0  sudh    12        18       24

In [2]:
d11 = {'a' : [1,2,3,4,5,'sudh']  , 
      'b' : [7,8,9,10,11,12],
      'c' : [13,14,15,16,17,18],
      'd' : [19,20,21,22,23,24]
      }

In [3]:
d12 = {'key1' : [1,2,3,4,5,'sudh'] , 
      'key2' : [7,8,9,'aman',11,12],
      'key3' : [13,14,'pwskills',16,17,18],
      'key4' : [19,20,21,'ineuron',23,24]
      }

In [1]:
import pandas as pd

In [4]:
df11 = pd.DataFrame(d11)

In [5]:
df12 = pd.DataFrame(d12)

In [6]:
df11

a   b   c   d
0     1   7  13  19
1     2   8  14  20
2     3   9  15  21
3     4  10  16  22
4     5  11  17  23
5  sudh  12  18  24

In [7]:
df12

key1  key2      key3     key4
0     1     7        13       19
1     2     8        14       20
2     3     9  pwskills       21
3     4  aman        16  ineuron
4     5    11        17       23
5  sudh    12        18       24

In [9]:
pd.concat([df11,df12] , axis = 0)

a     b     c     d  key1  key2      key3     key4
0     1   7.0  13.0  19.0   NaN   NaN       NaN      NaN
1     2   8.0  14.0  20.0   NaN   NaN       NaN      NaN
2     3   9.0  15.0  21.0   NaN   NaN       NaN      NaN
3     4  10.0  16.0  22.0   NaN   NaN       NaN      NaN
4     5  11.0  17.0  23.0   NaN   NaN       NaN      NaN
5  sudh  12.0  18.0  24.0   NaN   NaN       NaN      NaN
0   NaN   NaN   NaN   NaN     1     7        13       19
1   NaN   NaN   NaN   NaN     2     8        14       20
2   NaN   NaN   NaN   NaN     3     9  pwskills       21
3   NaN   NaN   NaN   NaN     4  aman        16  ineuron
4   NaN   NaN   NaN   NaN     5    11        17       23
5   NaN   NaN   NaN   NaN  sudh    12        18       24

In [10]:
pd.concat([df11,df12] , axis = 1)

a   b   c   d  key1  key2      key3     key4
0     1   7  13  19     1     7        13       19
1     2   8  14  20     2     8        14       20
2     3   9  15  21     3     9  pwskills       21
3     4  10  16  22     4  aman        16  ineuron
4     5  11  17  23     5    11        17       23
5  sudh  12  18  24  sudh    12        18       24

In [4]:
import numpy as np

In [5]:
l = [1,2,3,4,5,6]

In [6]:
type(l)

list

In [7]:
a = np.array(l)

In [8]:
type(a)

numpy.ndarray

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [12]:
a1 = np.array([[1,2,3],[3,4,5]])

In [13]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [16]:
a2 = np.array([[[1,2,3],[4,0.5,6]]])

In [17]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [22]:
a.ndim

1

In [23]:
a1.ndim

2

In [24]:
a2.ndim

3

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
type(l)

list

In [6]:
a =np.array(l)

In [7]:
type(a)

numpy.ndarray

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([[1,2,3],[4,5,6]])

In [10]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a2 = np.array([[[1,2,3],[4,0.5,6]]])

In [14]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [15]:
a.ndim

1

In [16]:
a1.ndim

2

In [17]:
a2.ndim

3

In [18]:
a3 = np.array([[[1,2,3],[4,0.5,6]],[[1,2,3],[4,0.5,6]],[[1,2,3],[4,0.5,6]]])

In [19]:
a3.ndim

3

In [20]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [21]:
l = [1,2,3,4]

In [24]:
a = np.asanyarray(l)

In [25]:
a

array([1, 2, 3, 4])

In [27]:
m= np.matrix(l)

In [28]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [29]:
a

array([1, 2, 3, 4])

In [30]:
a1 = a

In [31]:
a1

array([1, 2, 3, 4])

In [32]:
a

array([1, 2, 3, 4])

In [33]:
a[0]

1

In [36]:
a[0] = 10

In [38]:
a

array([10,  2,  3,  4])

In [37]:
a1[0:3]

array([10,  2,  3])

In [39]:
a2 = np.copy(a)

In [40]:
a2

array([10,  2,  3,  4])

In [41]:
a[3] = 50

In [46]:
a

array([10,  2,  3, 50])

In [43]:
a2

array([10,  2,  3,  4])

In [44]:
a2[3] = 30

In [45]:
a2

array([10,  2,  3, 30])

In [47]:
np.fromfunction(lambda  i,j : i == j ,(3,4) )

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [49]:
np.random.rand(2,3,2)

array([[[0.02302114, 0.44843737],
        [0.44919904, 0.01398651],
        [0.31300944, 0.76444406]],

       [[0.69088558, 0.16274984],
        [0.5475193 , 0.19144299],
        [0.82246849, 0.72478735]]])

In [50]:
np.random.rand(2,3,3,4)

array([[[[0.23571617, 0.58648953, 0.74027556, 0.17265183],
         [0.03071162, 0.16961829, 0.90989639, 0.07311997],
         [0.99056206, 0.21028063, 0.31957449, 0.10199995]],

        [[0.10462919, 0.23628754, 0.23643232, 0.55216348],
         [0.62619135, 0.74463763, 0.58703384, 0.2265791 ],
         [0.29827747, 0.857994  , 0.9483199 , 0.26524549]],

        [[0.98762079, 0.66649345, 0.177956  , 0.35634937],
         [0.11318708, 0.57006147, 0.74770138, 0.55783544],
         [0.98785786, 0.79866744, 0.31291782, 0.25817041]]],


       [[[0.76662439, 0.08957113, 0.48871554, 0.76997047],
         [0.50502665, 0.64650043, 0.50319777, 0.04142552],
         [0.36052437, 0.09122737, 0.60690302, 0.07202378]],

        [[0.64884815, 0.54526114, 0.27045588, 0.85328021],
         [0.98609409, 0.01782803, 0.91178592, 0.86295376],
         [0.76554502, 0.93032037, 0.35468899, 0.08644276]],

        [[0.53552515, 0.89151728, 0.05974772, 0.3045153 ],
         [0.88107715, 0.62413202, 0.3201643 

In [52]:
np.random.randn(2,3,2) # mean is 0 and Std = 1

array([[[-0.20451571,  0.43470297],
        [ 0.19044347,  0.80183199],
        [ 0.51979358, -0.68390969]],

       [[-0.81702239,  0.47378364],
        [ 0.20037792, -0.21337499],
        [ 0.99852965, -0.17996765]]])

In [69]:
d1 = np.random.randint(0,3,(4,4,2))

In [71]:
d1

array([[[2, 1],
        [0, 1],
        [1, 2],
        [0, 1]],

       [[1, 2],
        [0, 0],
        [0, 0],
        [1, 1]],

       [[1, 2],
        [0, 1],
        [2, 1],
        [0, 1]],

       [[2, 0],
        [0, 2],
        [2, 2],
        [1, 0]]])

In [83]:
d1 = d1.reshape(1,32)

In [85]:
d1

array([[2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 2, 1,
        0, 1, 2, 0, 0, 2, 2, 2, 1, 0]])

In [62]:
d = np.random.randn(3,4)

In [63]:
d

array([[-0.72725363,  0.39075585,  0.72002594,  0.56516299],
       [ 0.60982113, -1.57772079,  0.09458036, -1.01018986],
       [-2.38754612, -0.60455869,  1.23448711, -1.28812033]])

In [66]:
import pandas as pd

In [67]:
pd.DataFrame(d)

0         1         2         3
0 -0.727254  0.390756  0.720026  0.565163
1  0.609821 -1.577721  0.094580 -1.010190
2 -2.387546 -0.604559  1.234487 -1.288120

In [84]:
pd.DataFrame(d1)

0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  28  \
0   2   1   0   1   1   2   0   1   1   2  ...   0   1   2   0   0   2   2   

   29  30  31  
0   2   1   0  

[1 rows x 32 columns]

In [93]:
d = open("test2.xlsx" , 'r+')

In [87]:
d.read()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 10: invalid continuation byte

In [91]:
d.close()

In [90]:
d.writelines("hii add this")

In [94]:
d.readline()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 10: invalid continuation byte

In [99]:
import numpy as np

In [100]:
range(10)

range(0, 10)

In [101]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [107]:
np.arange(0.5,10) # can upper and lowerbound even in float to create range even in negitive axis(advance mode of range function)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [108]:
np.arange(5,-4,-1) 

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [109]:
np.arange(5,-4,-0.5) 

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [111]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [114]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [115]:
list(np.linspace(1,5,20 , retstep= True))

[array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367]

In [121]:
list(np.logspace(1,50,10))

[10.0,
 2782559.402207126,
 774263682681.1278,
 2.1544346900318954e+17,
 5.994842503189421e+22,
 1.6681005372000557e+28,
 4.6415888336128293e+33,
 1.2915496650148933e+39,
 3.59381366380464e+44,
 1e+50]

In [122]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [124]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [125]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [131]:
np.ones((3,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [133]:
np.ones((3,4,2))+ 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [135]:
np.ones((3,4,2)) * 10

array([[[10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.]]])

In [140]:
np.empty((4,3))

array([[0.72725363, 0.39075585, 0.72002594],
       [0.56516299, 0.60982113, 1.57772079],
       [0.09458036, 1.01018986, 2.38754612],
       [0.60455869, 1.23448711, 1.28812033]])

In [141]:
np.empty((2,3))

array([[1. , 2. , 3. ],
       [4. , 0.5, 6. ]])

In [145]:
 a = np.eye(6)

In [147]:
a.shape

(6, 6)

In [149]:
a.size

36

In [151]:
a.ndim

2

In [152]:
a1 = np.random.rand(3,4)

In [153]:
a1

array([[0.41887295, 0.36678162, 0.31555216, 0.72294857],
       [0.70673071, 0.1638363 , 0.13646295, 0.73730075],
       [0.84621931, 0.94981889, 0.76207178, 0.81453019]])

In [160]:
a1[0:1][0:1]

array([[0.41887295, 0.36678162, 0.31555216, 0.72294857]])

In [155]:
import pandas as pd

In [158]:
pd.DataFrame(a1)

0         1         2         3
0  0.418873  0.366782  0.315552  0.722949
1  0.706731  0.163836  0.136463  0.737301
2  0.846219  0.949819  0.762072  0.814530

In [161]:
a1[0:2,0:2]

array([[0.41887295, 0.36678162],
       [0.70673071, 0.1638363 ]])

In [167]:
a1[0:2,0:2]

array([[0.41887295, 0.36678162],
       [0.70673071, 0.1638363 ]])

In [172]:
a1[2: , [3]]

array([[0.81453019]])

In [178]:
m1 = np.random.randint(1,4,(3,3))

In [179]:
m1

array([[1, 1, 1],
       [2, 1, 2],
       [3, 2, 2]])

In [175]:
m2 = np.random.randint(2,4,(3,3))

In [182]:
m1

array([[1, 1, 1],
       [2, 1, 2],
       [3, 2, 2]])

In [177]:
m2

array([[2, 3, 2],
       [3, 2, 3],
       [3, 3, 3]])

In [180]:
m1*m2

array([[2, 3, 2],
       [6, 2, 6],
       [9, 6, 6]])

In [181]:
m1@m2

array([[ 8,  8,  8],
       [13, 14, 13],
       [18, 19, 18]])

In [1]:
m1

NameError: name 'm1' is not defined

In [2]:
import numpy as np

In [4]:
m1 = np.random.randint(1,4,(3,3))

In [7]:
m2 = np.random.randint(2,4,(3,3))

In [5]:
m1

array([[3, 1, 3],
       [2, 1, 1],
       [3, 2, 3]])

In [8]:
m2

array([[2, 3, 3],
       [2, 2, 3],
       [2, 2, 2]])

In [9]:
pow(m1,2)

array([[9, 1, 9],
       [4, 1, 1],
       [9, 4, 9]])

In [10]:
np.sqrt(m1)

array([[1.73205081, 1.        , 1.73205081],
       [1.41421356, 1.        , 1.        ],
       [1.73205081, 1.41421356, 1.73205081]])

In [12]:
np.log10(m1)

array([[0.47712125, 0.        , 0.47712125],
       [0.30103   , 0.        , 0.        ],
       [0.47712125, 0.30103   , 0.47712125]])

In [13]:
np.exp(m1)

array([[20.08553692,  2.71828183, 20.08553692],
       [ 7.3890561 ,  2.71828183,  2.71828183],
       [20.08553692,  7.3890561 , 20.08553692]])